### ISSUE TITLE
Добавить руки на RoundView

### ISSUE THREAD

**Issue by Artemaj9** [Artemaj9/EpicRPS#6]
Добавить  все возможные комбинации рук, "пятно" и текст между ними на RoundView. 
На вход передается состояние каждой руки (для женской - 5 вариантов), для мужской - 4
Как я понял, тут количество возможных комбинаций  рук -  13
Варианты текста: Fight, Lose, Win, Draw. 
Также нужно скрывать текст в зависимости от логичиской переменной

**Comment by EKukarskiy** [comment]
Done. Please review it.
